/** This file is auto-generated by Plasmic; please do not edit! */

import * as React from 'react';
import PlasmicLoader from '@plasmicapp/loader';

export default function PageComponent() {
    return <PlasmicLoader projectId="b48wmqCFKZPE5zP36D46Y9" component="Homepage"  />
}